apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    name: app
    type: netapi
spec:
  containers:
  - name: app-api
    image: andrescrca/net-sql-vaxi:v1.0
    ports:
      - containerPort: 5000
    env:
      - name: ConnectionStrings__SQLServerConnection
        value: Data Source=mssql-service; Initial Catalog=InmuebleDB; User Id=sa;password=Aa123456789
